site_name: Computer Engineering KB
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
  features:
    - navigation.tabs
    - search.share

exclude_patterns:
  - "*.py"
  - ".github/**/*"
  - "requirements.txt"
  - ".vscode/**/*"

plugins:
  - search
